"""add manager cash operations

Revision ID: 40a2f662c984
Revises: 48b98ec03172
Create Date: 2026-09-22 02:44:30.120292

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40a2f662c984'
down_revision: str | Sequence[str] | None = '48b98ec03172'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("operation_type IN ('CREDIT', 'DEBIT')", name='ck_cash_operations_type'),
    sa.CheckConstraint('amount > 0', name='ck_cash_operations_amount_positive'),
    sa.CheckConstraint('balance_before >= 0 AND balance_after >= 0', name='ck_cash_operations_balances_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_cash_operations_idempotency_key')
    )
    op.create_index(op.f('ix_cash_operations_account_id'), 'cash_operations', ['account_id'], unique=False)
    op.create_index(op.f('ix_cash_operations_manager_id'), 'cash_operations', ['manager_id'], unique=False)
    op.create_index(op.f('ix_cash_operations_operation_type'), 'cash_operations', ['operation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_operations_operation_type'), table_name='cash_operations')
    op.drop_index(op.f('ix_cash_operations_manager_id'), table_name='cash_operations')
    op.drop_index(op.f('ix_cash_operations_account_id'), table_name='cash_operations')
    op.drop_table('cash_operations')
    # ### end Alembic commands ###
