"""add transaction risk processing

Revision ID: 85868466cf2f
Revises: d27a793e994d
Create Date: 2026-09-19 03:00:20.898133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85868466cf2f'
down_revision: Union[str, Sequence[str], None] = 'd27a793e994d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_risk_jobs_attempts_non_negative'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_jobs_available_at'), 'risk_jobs', ['available_at'], unique=False)
    op.create_index(op.f('ix_risk_jobs_status'), 'risk_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_risk_jobs_transaction_id'), 'risk_jobs', ['transaction_id'], unique=True)
    op.add_column('transactions', sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('risk_decision', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('risk_processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        "ck_transactions_risk_score_range",
        "transactions",
        "risk_score >= 0 AND risk_score <= 100",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_transactions_risk_score_range",
        "transactions",
        type_="check",
    )
    op.drop_column('transactions', 'risk_processed_at')
    op.drop_column('transactions', 'risk_decision')
    op.drop_column('transactions', 'risk_score')
    op.drop_index(op.f('ix_risk_jobs_transaction_id'), table_name='risk_jobs')
    op.drop_index(op.f('ix_risk_jobs_status'), table_name='risk_jobs')
    op.drop_index(op.f('ix_risk_jobs_available_at'), table_name='risk_jobs')
    op.drop_table('risk_jobs')
    # ### end Alembic commands ###
